export const GET_WAREHOUSE = 'GET_WAREHOUSE';
export const SEARCH_WAREHOUSE = 'SEARCH_WAREHOUSE';
export const SET_LOADING = 'SET_LOADING';
export const WAREHOUSE_ERROR = 'WAREHOUSE_ERROR';
export const FILTER_CITY = 'FILTER_CITY';
export const FILTER_CLUSTER = 'FILTER_CLUSTER';
export const FILTER_SPACE = 'FILTER_SPACE';
export const GET_WAREHOUSES = 'GET_WAREHOUSES';
